version: '3'

services:
  nginx:
    # image: nginx:latest
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    networks:
      - app-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - ./zookeeper/data:/data
      - ./zookeeper/datalog:/datalog
    networks:
      - app-network

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "flume_topic:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - ./kafka/data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    networks:
      - app-network

  flume:
    image: probablyfine/flume:latest
    # image: probablyfine/flume:2.0.0
    volumes:
      - ./flume/conf/flume-kafka.conf:/opt/flume-config/flume.conf
      - ./flume/conf/log4j.properties:/opt/flume-config/log4j.properties
      - ./nginx/logs:/var/log/nginx:ro
    depends_on:
      - kafka
      - nginx
    command: ["flume-ng", "agent", "--conf-file", "/opt/flume-config/flume.conf"]
    environment:
      - FLUME_AGENT_NAME=agent1
      - JAVA_OPTS="-Dlog4j.configuration=file:///opt/flume-config/log4j.properties"
    networks:
      - app-network

  clickhouse-server:
    # image: clickhouse/clickhouse-server:latest
    # 或者使用特定版本
    image: clickhouse/clickhouse-server:22.3.3.44
    platform: linux/arm64
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse/data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=bi
      - CLICKHOUSE_USER=testing
      - CLICKHOUSE_PASSWORD=passwd
      - CLICKHOUSE_MAX_SERVER_MEMORY_USAGE=2147483648
      - CLICKHOUSE_MAX_SERVER_MEMORY_USAGE_TO_RAM_RATIO=0.9
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
